In [22]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(pd.__version__)
print(np.__version__)


2.4.1
2.2.2
1.26.4


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using `torch.Tensor()` https://pytorch.org/docs/stable/tensors.html

In [23]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [25]:
scalar.ndim

0

In [27]:
# Get tensor back as Python int
scalar.item()

7

In [28]:
#Vector 
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [29]:
vector.ndim

1

In [30]:
vector.shape

torch.Size([2])

In [32]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [34]:
# Check number of dimensions
MATRIX.ndim

2

In [35]:
MATRIX.shape

torch.Size([2, 2])

In [36]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [37]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [38]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [45]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

random tensors are important because the way many neuronal networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data 

In [47]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8383, 0.6457, 0.1541, 0.6316],
        [0.2508, 0.3729, 0.9798, 0.3455],
        [0.1950, 0.1950, 0.6843, 0.2370]])

In [50]:
random_tensor.shape

torch.Size([3, 4])

In [51]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [52]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [53]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range of tensors and tensors-likee

In [59]:
#Use torch.range()

zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:

1. Tensors not right datatype
2. Tensros not right shape
3. Tensors not on the right device


In [66]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [67]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [69]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not rigth datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not rigth shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the rigth device - to get device from a tensor, can use `tensor.device`
   

In [70]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4069, 0.6353, 0.4340, 0.7854],
        [0.8650, 0.4341, 0.5606, 0.1797],
        [0.8935, 0.0962, 0.9279, 0.5182]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating Tensors (tensor operations)

Tensor operatios includes:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [71]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [72]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [73]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [74]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [75]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [76]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [77]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])

In [79]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix multiplication

Two main ways of performing mulltiplication in neural networks and deep learning:

1. ELement-wise multiplication
2. Matrix multiplication (dot product)



In [80]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [81]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [82]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [83]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 1.04 ms


tensor(14)

In [84]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [85]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [86]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [87]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [88]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [89]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [91]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [92]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [93]:
#also can be done like this
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [94]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Reshapin, stacking squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unqueeze - add a `1` dimensions to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way
  

In [95]:
#let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [102]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [100]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 9)
z, z.shape

#view makes z point same direction as x so if z changes x changes too

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [103]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [115]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [105]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [131]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [132]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [140]:
x_original = torch.rand(size=(7, 5, 3))
x_original

tensor([[[0.2193, 0.5294, 0.2698],
         [0.9322, 0.5317, 0.4661],
         [0.3601, 0.9904, 0.0273],
         [0.2808, 0.6948, 0.0962],
         [0.2983, 0.8808, 0.6013]],

        [[0.3485, 0.5699, 0.6422],
         [0.8150, 0.9009, 0.6304],
         [0.0217, 0.5760, 0.4768],
         [0.6571, 0.5655, 0.1609],
         [0.2422, 0.3548, 0.3340]],

        [[0.4392, 0.9391, 0.4000],
         [0.1045, 0.4483, 0.0278],
         [0.9481, 0.2142, 0.6999],
         [0.1373, 0.0121, 0.5612],
         [0.6290, 0.2818, 0.2984]],

        [[0.8165, 0.8263, 0.7019],
         [0.8124, 0.0263, 0.4569],
         [0.4362, 0.5804, 0.5199],
         [0.4214, 0.1789, 0.9411],
         [0.9914, 0.0808, 0.6840]],

        [[0.7651, 0.9202, 0.5386],
         [0.9199, 0.8515, 0.4531],
         [0.5859, 0.8931, 0.2063],
         [0.1486, 0.0312, 0.4528],
         [0.8723, 0.9390, 0.1460]],

        [[0.0618, 0.6243, 0.3532],
         [0.2057, 0.4249, 0.2138],
         [0.9521, 0.3677, 0.1435],
         [

In [141]:
x_permuted = x_original.permute(2, 0, 1)
x_permuted

tensor([[[0.2193, 0.9322, 0.3601, 0.2808, 0.2983],
         [0.3485, 0.8150, 0.0217, 0.6571, 0.2422],
         [0.4392, 0.1045, 0.9481, 0.1373, 0.6290],
         [0.8165, 0.8124, 0.4362, 0.4214, 0.9914],
         [0.7651, 0.9199, 0.5859, 0.1486, 0.8723],
         [0.0618, 0.2057, 0.9521, 0.2853, 0.9384],
         [0.1004, 0.4176, 0.6170, 0.1219, 0.4431]],

        [[0.5294, 0.5317, 0.9904, 0.6948, 0.8808],
         [0.5699, 0.9009, 0.5760, 0.5655, 0.3548],
         [0.9391, 0.4483, 0.2142, 0.0121, 0.2818],
         [0.8263, 0.0263, 0.5804, 0.1789, 0.0808],
         [0.9202, 0.8515, 0.8931, 0.0312, 0.9390],
         [0.6243, 0.4249, 0.3677, 0.5407, 0.8414],
         [0.9476, 0.9887, 0.1629, 0.8070, 0.0996]],

        [[0.2698, 0.4661, 0.0273, 0.0962, 0.6013],
         [0.6422, 0.6304, 0.4768, 0.1609, 0.3340],
         [0.4000, 0.0278, 0.6999, 0.5612, 0.2984],
         [0.7019, 0.4569, 0.5199, 0.9411, 0.6840],
         [0.5386, 0.4531, 0.2063, 0.4528, 0.1460],
         [0.3532, 0.2138, 0

### Indexing (selecting data from tensors)

Indexing with python is similar to indexing with NumPy

In [163]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [164]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [165]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [166]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [167]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [168]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

### PyTorch tensors & NumPy

In [172]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

# Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [171]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [173]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [174]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take the random out of random)

In short how a nuronal network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again ->again`

to reduxe the randomness in neuronal networks and Pythorch comes the concept of a **random seed**.
Essentially what the random seed does is 'flavour' the randomness. )

In [176]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.1778, 0.8553, 0.2776, 0.3030],
        [0.0276, 0.6671, 0.0262, 0.6112],
        [0.6013, 0.0435, 0.3963, 0.5379]])

Tensor B:
tensor([[0.4860, 0.7050, 0.8800, 0.0806],
        [0.7151, 0.1021, 0.8530, 0.2032],
        [0.4238, 0.1386, 0.3690, 0.2029]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [185]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below

torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])